// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"vtuanjs/my-project/internal/controller"
	"vtuanjs/my-project/internal/repo"
	"vtuanjs/my-project/internal/service"
)

// Injectors from user.go:

func InitUserRouterHandler() (*controller.UserController, error) {
	iUserRepo := repo.NewUserRepo()
	iUserService := service.NewUserService(iUserRepo)
	userController := controller.NewUserController(iUserService)
	return userController, nil
}
