server:
  port: 8002
  mode: "prod"
postgres:
  host: postgres_go
  port: 5432
  username: postgres
  password: postgres
  dbname: shopdevgo
  maxIdleConns: 10
  maxOpenConns: 100
  connMaxLifetime: 3600
log:
  level: debug
  filename: ./log/dev.001.log
  maxSize: 300
  maxBackups: 3
  maxAge: 30
  compress: true
redis:
  host: redis_go
  port: 6379
  password: ""
  db: 0
